### ISSUE TITLE
Issue using `sendMessage` in a loop!!!

### ISSUE THREAD

**Issue by artknight** [mjclemente/mailgun.cfc#8]
Noticed an issue when using `sendMessage` in a loop. It keeps on sending all the emails to the first recipient in the array.

Thanks,
Art

**Comment by mjclemente** [comment]
Hi @artknight - yeesh - that's not good!

Can you give me a little code to reproduce the issue and I'll try to address it?

**Comment by artknight** [comment]
It turned out to be an issue on my end where the "to" address was outside
of the loop causing all emails to go to that one address.

Thank you though for reaching out! Great module!

Arthur

**Comment by mjclemente** [comment]
Glad it's working for you - have a great weekend!
